# Generated by Django 5.0.3 on 2024-03-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0003_alter_count_number_alter_totalcount_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='totalcount',
            name='total',
            field=models.IntegerField(),
        ),
    ]
