# Generated by Django 5.0.3 on 2024-03-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0005_alter_totalcount_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='count',
            name='title',
            field=models.CharField(default='count', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='totalcount',
            name='title',
            field=models.CharField(default='total_count', max_length=200, null=True),
        ),
    ]
