# Generated by Django 5.0.3 on 2024-03-23 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0006_count_title_totalcount_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalcount',
            name='numbers',
            field=models.ManyToManyField(null=True, to='count.count'),
        ),
    ]
